stages:
  - test
#  - build

variables:
  RUST_BACKTRACE: "1"

test:
  stage: test
  image: rust:1.80
  before_script:
    - rustup update
  script:
    - cargo test

# build:
#   stage: build
#   image: rust:1.80
#   before_script:
#    - rustup update
#   script:
#    - cargo build --release

# security:
#   stage: security
#   image: rust:1.80
#   before_script:
#     - rustup update
#     - cargo install cargo-audit || echo "cargo-audit already installed"
#   script:
#     - cargo audit
#   allow_failure: true