stages:
  - test
  - build
  - security

variables:
  RUST_BACKTRACE: "1"

test:
  stage: test
  image: rust:1.80
  script:
    - make test

build:
  stage: build
  image: rust:1.80
  script:
   - make build

security:
  stage: security
  image: rust:1.80
  before_script:
    - cargo install cargo-audit || echo "cargo-audit already installed"
  script:
    - cargo audit
  allow_failure: true