
services:

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: urcovault 
      POSTGRES_PASSWORD: urcovault 
      POSTGRES_DB: urcovault

    volumes:
        - ./.data/docker/postgres/data:/var/lib/postgresql/data/