
services:

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tanukeys 
      POSTGRES_PASSWORD: tanukeys 
      POSTGRES_DB: tanukeys.kernel

    volumes:
        - ./.data/docker/postgres/data:/var/lib/postgresql/data/
