
services:

  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    volumes:
        - ./.data/docker/postgres/data:/var/lib/postgresql/data/
