
services:

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
        - ./.data/docker/postgres/data:/var/lib/postgresql/data/
    networks:
      - postgres-net

  tanukeys-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tanukeys-api
    depends_on:
      - postgres
    networks:
      - postgres-net
      - proxy-net
    ports:
      - 3030:3030

  caddy:
    image: caddy:latest
    container_name: caddy
    depends_on:
      - tanukeys-api
    volumes:
      - .data/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - .data/docker/caddy/data:/data
      - .data/docker/caddy/config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - proxy-net

networks:
  postgres-net:
  proxy-net:
    
