[package]
name = "main_http_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
serde = "1.0.208"
kernel = { path = "../../libs/kernel" }
domain_errors = { path = "../../libs/shared/domain_errors" }

[dev-dependencies]
actix-rt = "2"