name: Test & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 6 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make deps
    
    - name: Run tests
      run: make test
    

  dev-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make deps
    
    - name: Build
      run: make dev/build

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make deps
    
    - name: Build
      run: make build

